### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Antoniofo** [FabienChatton/RealmTech#13]
je me baladait et j'ai softcrash
![image](https://github.com/FabienChatton/RealmTech/assets/89939643/dab7249a-3e72-4a00-9b78-c2b5d28e235c)
06:59:02.714 [Tick Thread] ERROR ch.realmtech.server.tick.TickThread -- This uuid has already ben registered: InventoryComponent id: 53686, uuid: 022fcb23-d455-440d-964f-9b321e11ddcc
java.lang.IllegalStateException: This uuid has already ben registered: InventoryComponent id: 53686, uuid: 022fcb23-d455-440d-964f-9b321e11ddcc
        at ch.realmtech.server.ecs.system.UuidEntityManager.registerEntityIdWithUuid(UuidEntityManager.java:106)
        at ch.realmtech.server.ecs.system.InventoryManager.createInventoryUi(InventoryManager.java:480)
        at ch.realmtech.server.ecs.system.InventoryManager.createFurnace(InventoryManager.java:463)
        at ch.realmtech.server.level.cell.FurnaceEditEntity.lambda$createEntity$0(FurnaceEditEntity.java:40)
        at ch.realmtech.server.ecs.plugin.server.ExecuteOnContextServer.onCommun(ExecuteOnContextServer.java:38)
        at ch.realmtech.server.level.cell.FurnaceEditEntity.createEntity(FurnaceEditEntity.java:40)
        at ch.realmtech.server.serialize.cell.CellSerializerV4.lambda$fromBytes$0(CellSerializerV4.java:78)
        at ch.realmtech.server.ecs.system.MapManager.lambda$newCell$2(MapManager.java:255)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at ch.realmtech.server.ecs.system.MapManager.newCell(MapManager.java:255)
        at ch.realmtech.server.serialize.chunk.ChunkSerializerV9.fromBytes(ChunkSerializerV9.java:50)
        at ch.realmtech.server.serialize.chunk.ChunkSerializerV9.fromBytes(ChunkSerializerV9.java:16)
        at ch.realmtech.server.serialize.AbstractSerializerController.decodeVersionAndBytes(AbstractSerializerController.java:59)
        at ch.realmtech.server.serialize.AbstractSerializerController.decodeApplicationBytes(AbstractSerializerController.java:68)
        at ch.realmtech.server.serialize.AbstractSerializerController.decode(AbstractSerializerController.java:36)
        at ch.realmtech.server.ecs.system.SaveInfManager.readSavedInfChunk(SaveInfManager.java:150)
        at ch.realmtech.server.ecs.system.MapSystemServer.getCacheOrGenerateChunk(MapSystemServer.java:230)
        at ch.realmtech.server.ecs.system.MapSystemServer.end(MapSystemServer.java:127)
        at com.artemis.BaseSystem.process(BaseSystem.java:47)
        at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
        at com.artemis.World.process(World.java:385)
        at ch.realmtech.server.ecs.EcsEngineServer.process(EcsEngineServer.java:95)
        at ch.realmtech.server.tick.TickThread.run(TickThread.java:28)
06:59:02.718 [Tick Thread] INFO ch.realmtech.server.ServerContext -- Saving map...
06:59:02.767 [Tick Thread] INFO ch.realmtech.server.ecs.EcsEngineServer -- Map saved
06:59:02.768 [Tick Thread] INFO ch.realmtech.server.ServerContext -- Closing server...
06:59:02.782 [main] INFO ch.realmtech.server.ServerContext -- Saving map...
06:59:02.783 [main] ERROR ch.realmtech.core.game.ecs.ECSEngine -- Cannot invoke "ch.realmtech.server.ecs.system.MapManager.getInfMap()" because the return value of "ch.realmtech.server.ecs.plugin.server.SystemsAdminServer.getMapManager()" is null
java.lang.NullPointerException: Cannot invoke "ch.realmtech.server.ecs.system.MapManager.getInfMap()" because the return value of "ch.realmtech.server.ecs.plugin.server.SystemsAdminServer.getMapManager()" is null
        at ch.realmtech.server.ecs.EcsEngineServer.saveMap(EcsEngineServer.java:113)
        at ch.realmtech.server.ServerContext.save(ServerContext.java:177)
        at ch.realmtech.server.ServerContext.saveAndClose(ServerContext.java:142)
        at ch.realmtech.core.game.netty.ClientConnexionIntern.close(ClientConnexionIntern.java:38)
        at ch.realmtech.core.game.ecs.ECSEngine.dispose(ECSEngine.java:156)
        at ch.realmtech.core.RealmTech.lambda$closeEcs$2(RealmTech.java:346)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:209)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
        at ch.realmtech.core.DesktopLauncher.main(DesktopLauncher.java:16)

**Comment by FabienChatton** [comment]
Ok, sa se produit avec l'item de la case du haut.
C'est probalement quand la furnace est recharger dans le monde,
Du coup je penses que c'est l'item qui leak au dechargement

**Comment by FabienChatton** [comment]
je penses que c'est bon
