### ISSUE TITLE
Server is not standalone

### ISSUE THREAD

**Issue by Antoniofo** [FabienChatton/RealmTech#4]
When i built the server with
`./gradlew server:dist` 
and launches it with
`java -jar server-1.0.jar` 
It automatically crashes because it needs the client to create the RealmTechData folder for saving the world
here is the stacktrace i got

`16:37:02.108 [main] ERROR ch.realmtech.server.ServerContext -- RealmTechData/properties/optionsServer.cfg (No such file or directory)
java.io.FileNotFoundException: RealmTechData/properties/optionsServer.cfg (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at ch.realmtech.server.datactrl.OptionServer.getOptionFileAndLoadOrCreate(OptionServer.java:27)
        at ch.realmtech.server.ServerContext.reloadOption(ServerContext.java:169)
        at ch.realmtech.server.ServerContext.<init>(ServerContext.java:76)
        at ch.realmtech.server.ServerContext.main(ServerContext.java:111)
16:37:02.112 [main] INFO ch.realmtech.server.ServerContext -- Fermeture du serveur...
16:37:02.113 [main] ERROR ch.realmtech.server.ServerContext -- Option file can not be saved. Cannot invoke "ch.realmtech.server.datactrl.OptionServer.save()" because "this.optionServer" is null
Exception in thread "main" java.io.FileNotFoundException: RealmTechData/properties/optionsServer.cfg (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at ch.realmtech.server.datactrl.OptionServer.getOptionFileAndLoadOrCreate(OptionServer.java:27)
        at ch.realmtech.server.ServerContext.reloadOption(ServerContext.java:169)
        at ch.realmtech.server.ServerContext.<init>(ServerContext.java:76)
        at ch.realmtech.server.ServerContext.main(ServerContext.java:111)`

**Comment by FabienChatton** [comment]
sa devrait être fix
